// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXSyzBx5zONjtWbx27V1T8K_1OYlV5IK0',
    appId: '1:508377489981:web:a87252aba7fb2bea750054',
    messagingSenderId: '508377489981',
    projectId: 'kochat-12b25',
    authDomain: 'kochat-12b25.firebaseapp.com',
    storageBucket: 'kochat-12b25.appspot.com',
    measurementId: 'G-384YS70G91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVa2FCnQ_RRokZ7mpqMGFTfHy7-hO3vM',
    appId: '1:508377489981:android:b517fc6677c2b2fc750054',
    messagingSenderId: '508377489981',
    projectId: 'kochat-12b25',
    storageBucket: 'kochat-12b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHJ-8pwgxaAOh5_5epboDFZPQm4net-o',
    appId: '1:508377489981:ios:99b78e83770e2974750054',
    messagingSenderId: '508377489981',
    projectId: 'kochat-12b25',
    storageBucket: 'kochat-12b25.appspot.com',
    androidClientId: '508377489981-bkdr36ugoa2uo0erh3gksbqefq2nkf1u.apps.googleusercontent.com',
    iosClientId: '508377489981-i00lrrf3qc8s80oeo865rddp71geul1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.kochat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDHJ-8pwgxaAOh5_5epboDFZPQm4net-o',
    appId: '1:508377489981:ios:0e384274411c77c3750054',
    messagingSenderId: '508377489981',
    projectId: 'kochat-12b25',
    storageBucket: 'kochat-12b25.appspot.com',
    androidClientId: '508377489981-bkdr36ugoa2uo0erh3gksbqefq2nkf1u.apps.googleusercontent.com',
    iosClientId: '508377489981-cnth10pmas7cl00f5snl9irjv7husuuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kochat.RunnerTests',
  );
}
